name: evaluate all bets
on:
  schedule:
    # Run at the top of every odd-numbered hour (1, 3, 5, ..., 23 UTC)
    - cron: "0 1-23/2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --default-timeout=100

      - name: Clean up bet timestamps
        run: python scripts/cleanup_bet_timestamps.py

      - name: Evaluate NBA bets
        run: python scripts/nba_evaluate_bets.py

      - name: Evaluate NCAAB bets
        run: python scripts/ncaab_evaluate_bets.py

      - name: Evaluate Soccer bets
        run: python scripts/soccer_evaluate_bets.py

      - name: List files before push
        run: |
          ls -la
          git status

      - name: Commit and push changes
        run: |
          git config --global user.name "aaron"
          git config --global user.email "aaroncolesmith@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BET_MODEL_GITHUB_TOKEN }}
